### ISSUE TITLE
Publish for Scala 2.11.*

### ISSUE THREAD

**Issue by wpoosanguansit** [mlangc/slf4zio#1]
Hi,

Would it be possible to have the library published for Scala 2.11.*?  Thanks for your help.

**Comment by mlangc** [comment]
Sorry, I completely oversaw your message. Let me know if you are still interested... I think that publishing for scala-2.11 should not be a problem!

**Comment by wpoosanguansit** [comment]
That would be great.  Also, would you be able to advice how do we log code that forks?  Thanks for your help.

**Comment by mlangc** [comment]
I've just published 0.2.1 for scala-2.11 and scala-2.12 (it might take a few hours till this gets synced I guess). Let me know if you run into trouble. As for your other question, can you elaborate on that a bit?

**Comment by wpoosanguansit** [comment]
Thanks for your help.  For the issue of my code using fork, the log does not seem to be tracing the green threads that got spawn.  And I am not sure how can we trace code execution after .fork?  Thanks again for your help.

**Comment by mlangc** [comment]
You want something like [MDC](https://logback.qos.ch/manual/mdc.html), but aware of ZIO fibers? If so, that would be a very nice feature indeed, but I'm still unsure about the details.

**Comment by mlangc** [comment]
Maybe this is of interest for you too: https://twitter.com/jdegoes/status/1127364492621434882

**Comment by wpoosanguansit** [comment]
Thanks.  I did go through the talk but I could only get the trace when something throws exceptions though.  I still don’t know just how to trace all the code executions by turning on log levels.  And using MDC, could you recommend how to do that with your lib?  Appreciate your help.

**Comment by mlangc** [comment]
There is no support for MDC yet, and it is not clear if there will ever be, because I'm still unsure about how to implement this. As for your tracing question: Can you post a small example, together with the tracing output you would like to have?
